### ISSUE TITLE
Error when starting:    SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by jim-kirisame** [Monogramm/docker-taiga-back-base#8]
**Additional context**
It seems that [kombu has a bug on python 3.7](https://github.com/celery/kombu/issues/841), which would cause the following error. This bug fixed on kombu 4.2.0 but taiga still using kombu 4.0.2, so please consider downgrade the python to 3.6

**Describe the bug**
error when starting taiga-docker
```
taiga-back_1   | SyntaxError: invalid syntax
taiga-back_1   | [2019-03-25 01:47:32 +0000] [18] [ERROR] Exception in worker process
taiga-back_1   | Traceback (most recent call last):
taiga-back_1   |   File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
taiga-back_1   |     self.wsgi = self.app.wsgi()
taiga-back_1   |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
taiga-back_1   |     self.callable = self.load()
taiga-back_1   |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
taiga-back_1   |     return self.load_wsgiapp()
taiga-back_1   |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
taiga-back_1   |     return util.import_app(self.app_uri)
taiga-back_1   |   File "/usr/local/lib/python3.7/site-packages/gunicorn/util.py", line 352, in import_app
taiga-back_1   |     __import__(module)
taiga-back_1   |   File "/usr/src/taiga-back/taiga/__init__.py", line 19, in <module>
taiga-back_1   |     from . import celery
taiga-back_1   |   File "/usr/src/taiga-back/taiga/celery.py", line 21, in <module>
taiga-back_1   |     from celery import Celery
taiga-back_1   |   File "<frozen importlib._bootstrap>", line 1032, in _handle_fromlist
taiga-back_1   |   File "/usr/local/lib/python3.7/site-packages/celery/local.py", line 509, in __getattr__
taiga-back_1   |     module = __import__(self._object_origins[name], None, None, [name])
taiga-back_1   |   File "/usr/local/lib/python3.7/site-packages/celery/app/__init__.py", line 5, in <module>
taiga-back_1   |     from celery import _state
taiga-back_1   |   File "/usr/local/lib/python3.7/site-packages/celery/_state.py", line 15, in <module>
taiga-back_1   |     from celery.utils.threads import LocalStack
taiga-back_1   |   File "/usr/local/lib/python3.7/site-packages/celery/utils/__init__.py", line 10, in <module>
taiga-back_1   |     from .nodenames import worker_direct, nodename, nodesplit
taiga-back_1   |   File "/usr/local/lib/python3.7/site-packages/celery/utils/nodenames.py", line 7, in <module>
taiga-back_1   |     from kombu.entity import Exchange, Queue
taiga-back_1   |   File "/usr/local/lib/python3.7/site-packages/kombu/entity.py", line 6, in <module>
taiga-back_1   |     from .abstract import MaybeChannelBound, Object
taiga-back_1   |   File "/usr/local/lib/python3.7/site-packages/kombu/abstract.py", line 6, in <module>
taiga-back_1   |     from .connection import maybe_channel
taiga-back_1   |   File "/usr/local/lib/python3.7/site-packages/kombu/connection.py", line 893
taiga-back_1   |     return self.transport.implements.async
```

**To Reproduce**
docker-compose file:
```
version: '2'

services:
  taiga-back:
    image: monogramm/docker-taiga-back-base:latest
    depends_on:
      - postgres

    environment:
      TAIGA_HOSTNAME: localhost
      TAIGA_DB_HOST: postgres
      TAIGA_DB_NAME: taigadb
      TAIGA_DB_USER: taiga
      TAIGA_DB_PASSWORD: password

    volumes:
      - ./media:/usr/src/taiga-back/media
      - ./taiga-conf:/taiga

  taiga-front:
    image: monogramm/docker-taiga-front-base:latest
    ports:
      - 2380:80
    depends_on:
      - taiga-back
    environment:
      TAIGA_BACK_HOST: taiga-back
      TAIGA_BACK_PORT: 8001

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: taigadb
      POSTGRES_USER: taiga
      POSTGRES_PASSWORD: password
    ports:
      - 5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
```

**Docker (please complete the following information):**
 - Docker version 18.09.1, build 4c52b90
 - Image: latest
